spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true # for test
  profiles:
    active: secret

# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true