spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update # TODO push, merge 시 꼭 update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true # fetch join 으로 쿼리 최적화를 위해서 로깅 보기
        show_sql: false # TODO push, merge 시 꼭 false
  profiles:
    active: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true # 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true

# AWS 연결 오류 로그 안 띄우고 개발 환경에서 부트 빠르게 띄우는 설정
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error