spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false # for test TODO: PR 전 꼭 false 로 변경
  profiles:
    active: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true # 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true

