name: jsonWeb exit server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  S3_BUCKET_NAME: jsonweb-deploy

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v2
  
  - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'temurin'
  
  - name: Grant execute permission for gradlew
    run: chmod +x gradlew
    
  - name: Build with Gradle
    run: ./gradlew clean build
